tag_dict = {
   "aura:unescapedHtml":{
      "value":{
         "type":"String"
      }
   },
   "lightning:formattedDateTime":{
      "hour12":{
         "type":"Boolean"
      },
      "day":{
         "type":"String"
      },
      "value":{
         "type":"Object",
         "required": True
      },
      "timeZone":{
         "type":"String"
      },
      "weekday":{
         "type":"String"
      },
      "timeZoneName":{
         "type":"String"
      },
      "month":{
         "type":"String"
      },
      "second":{
         "type":"String"
      },
      "era":{
         "type":"String"
      },
      "hour":{
         "type":"String"
      },
      "minute":{
         "type":"String"
      },
      "year":{
         "type":"String"
      }
   },
   "aura:iteration":{
      "end":{
         "type":"Integer"
      },
      "items":{
         "type":"List",
         "required":True
      },
      "loaded":{
         "type":"Boolean"
      },
      "template":{
         "type":"Componentdefref[]"
      },
      "var":{
         "type":"String",
         "required":True
      },
      "indexVar":{
         "type":"String"
      },
      "body":{
         "type":"Componentdefref[]"
      },
      "start":{
         "type":"Integer"
      }
   },
   "aura:attribute":{
      "required":{
         "type":"Boolean"
      },
      "description":{
         "type":"String"
      },
      "access":{
         "type":"String"
      },
      "default":{
         "type":"String"
      },
      "type":{
         "type":"String"
      },
      "name":{
         "type":"String"
      }
   },
   "lightning:tab":{
      "onblur":{
         "type":"Action"
      },
      "tabindex":{
         "type":"Integer"
      },
      "onfocus":{
         "type":"Action"
      },
      "onactive":{
         "type":"Action"
      },
      "title":{
         "type":"String"
      },
      "label":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "accesskey":{
         "type":"String"
      },
      "id":{
         "type":"String"
      }
   },
   "auraStorage:init":{
      "debugLoggingEnabled":{
         "type":"Boolean"
      },
      "persistent":{
         "type":"Boolean"
      },
      "clearStorageOnInit":{
         "type":"Boolean"
      },
      "defaultAutoRefreshInterval":{
         "type":"Integer"
      },
      "defaultExpiration":{
         "type":"Integer"
      },
      "maxSize":{
         "type":"Integer"
      },
      "version":{
         "type":"String"
      },
      "secure":{
         "type":"Boolean"
      },
      "name":{
         "type":"String",
         "required": True
      }
   },
   "lightning:progressIndicator": {
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "currentStep":{
         "type":"String"
      },
      "hasError":{
         "type":"Boolean"
      },
      "type":{
         "type":"String"
      },
      "variant":{
         "type":"String"
      }
   },
   "lightning:progressBar": {
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "size":{
         "type":"String"
      },
      "value":{
         "type":"Integer"
      },
      "variant":{
         "type":"String"
      }
   },
   "lightning:path": {
      "onselect":{
         "type":"Action"
      },
      "hideUpdateButton":{
         "type":"Boolean"
      },
      "recordId":{
         "type":"String"
      },
      "variant":{
         "type":"String"
      }
   },
   "lightning:picklistPath": {
      "onselect":{
         "type":"Action"
      },
      "picklistFieldApiName":{
         "type":"String"
      },
      "recordId":{
         "type":"String"
      },
      "variant":{
         "type":"String"
      }
   },
   "lightning:outputField": {
      "class":{
         "type":"String"
      },
      "fieldName":{
         "type":"String",
         "required": True
      },
      "variant":{
         "type":"String"
      }
   },
   "aura:text": {
      "value":{
         "type":"String"
      }
   },
   "lightning:inputField": {
      "body":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "fieldName":{
         "type":"String"
      },
      "value":{
         "type":"String"
      },
      "onchange":{
         "type":"Action"
      }
   },
   "lightning:tabset":{
      "variant":{
         "type":"String"
      },
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "selectedTabId":{
         "type":"String"
      },
      "onselect":{
         "type":"Action"
      }
   },
   "ui:radioMenuItem":{
      "class":{
         "type":"String"
      },
      "type":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "hideMenuAfterSelected":{
         "type":"Boolean"
      },
      "selected":{
         "type":"Boolean"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:inputRadio":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "name":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "text":{
         "type":"String"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "required":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "aura:method":{
      "action":{
         "type":"Expression"
      },
      "description":{
         "type":"String"
      },
      "access":{
         "type":"String"
      },
      "name":{
         "type":"String"
      }
   },
   "lightning:Input":{
      "class":{
         "type":"String"
      },
      "validity":{
         "type":"Object"
      },
      "messageWhenPatternMismatch":{
         "type":"String"
      },
      "value":{
         "type":"Object"
      },
      "accesskey":{
         "type":"String"
      },
      "maxLength":{
         "type":"Integer"
      },
      "minlength":{
         "type":"Integer"
      },
      "type":{
         "type":"String"
      },
      "name":{
         "type":"String",
         "required": True
      },
      "checked":{
         "type":"Boolean"
      },
      "readonly":{
         "type":"Boolean"
      },
      "multiple":{
         "type":"Boolean"
      },
      "onfocus":{
         "type":"Action"
      },
      "max":{
         "type":"Decimal"
      },
      "pattern":{
         "type":"String"
      },
      "messageWhenBadInput":{
         "type":"String"
      },
      "accept":{
         "type":"String"
      },
      "messageToggleInactive":{
         "type":"String"
      },
      "messageToggleActive":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "isLoading":{
         "type":"Boolean"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "title":{
         "type":"String"
      },
      "messageWhenRangeOverflow":{
         "type":"String"
      },
      "messageWhenStepMismatch":{
         "type":"String"
      },
      "onchange":{
         "type":"Action"
      },
      "required":{
         "type":"Boolean"
      },
      "messageWhenValueMissing":{
         "type":"String"
      },
      "min":{
         "type":"Decimal"
      },
      "step":{
         "type":"Object"
      },
      "files":{
         "type":"Object"
      },
      "messageWhenTypeMismatch":{
         "type":"String"
      },
      "formatter":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "messageWhenTooLong":{
         "type":"String"
      },
      "messageWhenRangeUnderflow":{
         "type":"String"
      },
      "placeholder":{
         "type":"String"
      },
      "tabindex":{
         "type":"Integer"
      },
      "variant":{
         "type":"String"
      }
   },
   "lightning:datatable":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "columns":{
         "type":"List"
      },
      "data":{
         "type":"Object"
      },
      "defaultSortDirection":{
         "type":"String"
      },
      "enableInfiniteLoading":{
         "type":"Boolean"
      },
      "isLoading":{
         "type":"Boolean"
      },
      "keyField":{
         "type":"String",
         "required": True
      },
      "loadMoreOffset":{
         "type":"Integer"
      },
      "maxColumnWidth":{
         "type":"Integer"
      },
      "maxRowSelection":{
         "type":"Integer"
      },
      "minColumnWidth":{
         "type":"Integer"
      },
      "onheaderaction":{
         "type":"Action"
      },
      "onloadmore":{
         "type":"Action"
      },
      "onresize":{
         "type":"Action"
      },
      "onrowaction":{
         "type":"Action"
      },
      "onrowselection":{
         "type":"Action"
      },
      "onsort":{
         "type":"Action"
      },
      "resizeColumnDisabled":{
         "type":"Boolean"
      },
      "resizeStep":{
         "type":"Integer"
      },
      "rowNumberOffset":{
         "type":"Integer"
      },
      "selectedRows":{
         "type":"List"
      },
      "showRowNumberColumn":{
         "type":"Boolean"
      },
      "title":{
         "type":"String"
      },
      "sortedBy":{
         "type":"String"
      },
      "sortedDirection":{
         "type":"String"
      }
   },
   "lightning:layout":{
      "pullToBoundary":{
         "type":"String"
      },
      "class":{
         "type":"String"
      },
      "verticalAlign":{
         "type":"String"
      },
      "horizontalAlign":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "multipleRows":{
         "type":"Boolean"
      }
   },
   "lightning:layoutItem":{
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "smallDeviceSize":{
         "type":"Integer"
      },
      "flexibility":{
         "type":"Object"
      },
      "largeDeviceSize":{
         "type":"Integer"
      },
      "padding":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "mediumDeviceSize":{
         "type":"Integer"
      }
   },
   "ui:inputDate":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "format":{
         "type":"String"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "langLocale":{
         "type":"String"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "displayDatePicker":{
         "type":"Boolean"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "required":{
         "type":"Boolean"
      },
      "labelClass":{
         "type":"String"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:inputSelectOption":{
      "mouseup":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "click":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "name":{
         "type":"String"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "text":{
         "type":"String"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:outputPhone":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String",
         "required": True
      },
      "click":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "ui:outputCurrency":{
      "class":{
         "type":"String"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"BigDecimal",
         "required": True
      },
      "currencySymbol":{
         "type":"String"
      },
      "currencyCode":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "format":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "ltng:require":{
      "afterScriptsLoaded":{
         "type":"COMPONENT"
      },
      "styles":{
         "type":"String[]"
      },
      "scripts":{
         "type":"String[]"
      },
      "beforeLoadingResources":{
         "type":"COMPONENT"
      }
   },
   "ui:inputRichText":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "resizable":{
         "type":"Boolean"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "required":{
         "type":"Boolean"
      },
      "label":{
         "type":"String"
      },
      "width":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"ArrayList"
      },
      "placeholder":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "rows":{
         "type":"Integer"
      },
      "value":{
         "type":"Boolean"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "height":{
         "type":"String"
      },
      "cols":{
         "type":"Integer"
      },
      "readonly":{
         "type":"Boolean"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:menuTrigger":{
      "class":{
         "type":"String"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "title":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "menuTriggerPress":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:outputDate":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String",
         "required": True
      },
      "langLocale":{
         "type":"String"
      },
      "format":{
         "type":"String"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "lightning:icon":{
      "iconName":{
         "type":"String",
         "required": True
      },
      "class":{
         "type":"String"
      },
      "alternativeText":{
         "type":"String"
      },
      "size":{
         "type":"String"
      },
      "variant":{
         "type":"String"
      }
   },
   "ui:button":{
      "buttonTitle":{
         "type":"String"
      },
      "labelClass":{
         "type":"String"
      },
      "class":{
         "type":"String"
      },
      "press":{
         "type":"COMPONENT"
      },
      "buttonType":{
         "type":"String"
      },
      "accesskey":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "label":{
         "type":"String"
      }
   },
   "lightning:badge":{
      "class":{
         "type":"String"
      },
      "label":{
         "type":"String",
         "required": True
      }
   },
   "lightning:tile":{
      "class":{
         "type":"String"
      },
      "href":{
         "type":"String"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "media":{
         "type":"Component[]"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:tree":{
      "class":{
         "type":"String"
      },
      "items":{
         "type":"Object"
      },
      "label":{
         "type":"String"
      },
      "header":{
         "type":"String"
      },
      "onselect":{
         "type":"Action"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:pill":{
      "class":{
         "type":"String"
      },
      "href":{
         "type":"String"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "name":{
         "type":"String"
      },
      "onclick":{
         "type":"Action"
      },
      "onremove":{
         "type":"Action"
      },
      "media":{
         "type":"Component[]"
      },
      "hasError":{
         "type":"Boolean"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:pillContainer":{
      "class":{
         "type":"String"
      },
      "items":{
         "type":"List"
      },
      "label":{
         "type":"String"
      },
      "onitemremove":{
         "type":"Action"
      },
      "singleLine":{
         "type":"Boolean"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:breadcrumb":{
      "class":{
         "type":"String"
      },
      "href":{
         "type":"String"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "name":{
         "type":"String"
      },
      "onclick":{
         "type":"Action"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:breadcrumbs":{
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      }
   },
   "ui:inputTextArea":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "resizable":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "placeholder":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "rows":{
         "type":"Integer"
      },
      "value":{
         "type":"Boolean"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "cols":{
         "type":"Integer"
      },
      "readonly":{
         "type":"Boolean"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "ui:message":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "closable":{
         "type":"Boolean"
      },
      "severity":{
         "type":"String"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "title":{
         "type":"String"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "lightning:formattedNumber":{
      "minimumIntegerDigits":{
         "type":"Integer"
      },
      "value":{
         "type":"Decimal"
      },
      "maximumSignificantDigits":{
         "type":"Integer"
      },
      "currencyCode":{
         "type":"String"
      },
      "minimumFractionDigits":{
         "type":"Integer"
      },
      "style":{
         "type":"String"
      },
      "maximumFractionDigits":{
         "type":"Integer"
      },
      "currencyDisplayAs":{
         "type":"String"
      },
      "minimumSignificantDigits":{
         "type":"Integer"
      }
   },
   "ui:checkboxMenuItem":{
      "class":{
         "type":"String"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "selected":{
         "type":"Boolean"
      },
      "hideMenuAfterSelected":{
         "type":"Boolean"
      },
      "type":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "aura:registerEvent":{
      "type":{
         "type":"String"
      },
      "name":{
         "type":"String"
      }
   },
   "force:inputField":{
      "change":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "errorComponent":{
         "type":"COMPONENT[]"
      },
      "value":{
         "type":"Object"
      },
      "required":{
         "type":"Boolean"
      }
   },
   "ui:actionMenuItem":{
      "class":{
         "type":"String"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "selected":{
         "type":"Boolean"
      },
      "hideMenuAfterSelected":{
         "type":"Boolean"
      },
      "type":{
         "type":"String"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "label":{
         "type":"String"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "aura:html":{
      "tag":{
         "type":"String"
      },
      "HTMLAttributes":{
         "type":"Map"
      },
      "body":{
         "type":"Component[]"
      }
   },
   "force:canvasApp":{
      "displayLocation":{
         "type":"String"
      },
      "border":{
         "type":"String"
      },
      "watermark":{
         "type":"Boolean"
      },
      "maxHeight":{
         "type":"String"
      },
      "developerName":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "sublocation":{
         "type":"String"
      },
      "containerId":{
         "type":"String"
      },
      "width":{
         "type":"String"
      },
      "parameters":{
         "type":"String"
      },
      "scrolling":{
         "type":"String"
      },
      "onCanvasAppLoad":{
         "type":"String"
      },
      "onCanvasAppError":{
         "type":"String"
      },
      "maxWidth":{
         "type":"String"
      },
      "height":{
         "type":"String"
      },
      "applicationName":{
         "type":"String"
      },
      "namespacePrefix":{
         "type":"String"
      },
      "onCanvasSubscribed":{
         "type":"String"
      },
      "canvasId":{
         "type":"String"
      },
      "referenceId":{
         "type":"Id"
      }
   },
   "ui:menuList":{
      "class":{
         "type":"String"
      },
      "menuItems":{
         "type":"List"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "menuCollapse":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "visible":{
         "type":"Boolean"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "closeOnTabKey":{
         "type":"Boolean"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "menuExpand":{
         "type":"COMPONENT"
      },
      "autoPosition":{
         "type":"Boolean"
      },
      "menuFocusChange":{
         "type":"COMPONENT"
      },
      "closeOnClickOutside":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "menuSelect":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      }
   },
   "lightning:buttonMenu":{
      "class":{
         "type":"String"
      },
      "iconSize":{
         "type":"String"
      },
      "alternativeText":{
         "type":"String"
      },
      "value":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "iconName":{
         "type":"String"
      },
      "visible":{
         "type":"Boolean"
      },
      "accesskey":{
         "type":"String"
      },
      "name":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "tabindex":{
         "type":"Integer"
      },
      "onfocus":{
         "type":"Action"
      },
      "variant":{
         "type":"String"
      },
      "onselect":{
         "type":"Action"
      },
      "disabled":{
         "type":"Boolean"
      },
      "menuAlignment":{
         "type":"String"
      }
   },
   "ui:inputCheckbox":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "name":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "text":{
         "type":"String"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "required":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:inputSecret":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "forceChatter:fullFeed":{
      "subjectId":{
         "type":"String"
      },
      "type":{
         "type":"String"
      },
      "handleNavigationEvents":{
         "type":"Boolean"
      }
   },
   "ui:inputDefaultError":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String[]"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "ui:menu":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "force:outputField":{
      "class":{
         "type":"String"
      },
      "value":{
         "type":"Object"
      }
   },
   "lightning:buttonIcon":{
      "class":{
         "type":"String"
      },
      "alternativeText":{
         "type":"String",
         "required": True
      },
      "value":{
         "type":"String"
      },
      "size":{
         "type":"String"
      },
      "iconName":{
         "type":"String",
         "required": True
      },
      "iconClass":{
         "type":"String"
      },
      "accesskey":{
         "type":"String"
      },
      "name":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "tabindex":{
         "type":"Integer"
      },
      "title":{
         "type":"String"
      },
      "type":{
         "type":"String"
      },
      "onfocus":{
         "type":"Action"
      },
      "variant":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "onclick":{
         "type":"Action"
      }
   },
   "lightning:buttonIconStateful":{
      "class":{
         "type":"String"
      },
      "alternativeText":{
         "type":"String",
         "required": True
      },
      "value":{
         "type":"String"
      },
      "size":{
         "type":"String"
      },
      "iconName":{
         "type":"String",
         "required": True
      },
      "iconClass":{
         "type":"String"
      },
      "accesskey":{
         "type":"String"
      },
      "name":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "tabindex":{
         "type":"Integer"
      },
      "selected":{
         "type":"Boolean"
      },
      "title":{
         "type":"String"
      },
      "type":{
         "type":"String"
      },
      "onfocus":{
         "type":"Action"
      },
      "variant":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "onclick":{
         "type":"Action"
      }
   },
   "lightning:buttonStateful":{
      "class":{
         "type":"String"
      },
      "labelWhenOff":{
         "type":"String",
         "required": True
      },
      "labelWhenOn":{
         "type":"String",
         "required": True
      },
      "iconNameWhenOff":{
         "type":"String"
      },
      "iconNameWhenOn":{
         "type":"String"
      },
      "labelWhenHover":{
         "type":"String"
      },
      "iconNameWhenHover":{
         "type":"String",
      },
      "accesskey":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "tabindex":{
         "type":"Integer"
      },
      "title":{
         "type":"String"
      },
      "onfocus":{
         "type":"Action"
      },
      "variant":{
         "type":"String"
      },
      "state":{
         "type":"Boolean"
      },
      "onclick":{
         "type":"Action"
      }
   },
   "ui:outputDateTime":{
      "class":{
         "type":"String"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String",
         "required": True
      },
      "timezone":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "format":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "langLocale":{
         "type":"String"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "ui:inputDateTime":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "format":{
         "type":"String"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "langLocale":{
         "type":"String"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "displayDatePicker":{
         "type":"Boolean"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "required":{
         "type":"Boolean"
      },
      "labelClass":{
         "type":"String"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:menuItemSeparator":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "lightning:select":{
      "class":{
         "type":"String"
      },
      "onchange":{
         "type":"Action"
      },
      "value":{
         "type":"String"
      },
      "required":{
         "type":"Boolean"
      },
      "accesskey":{
         "type":"String"
      },
      "name":{
         "type":"String",
         "required": True
      },
      "validity":{
         "type":"Object"
      },
      "tabindex":{
         "type":"Integer"
      },
      "onfocus":{
         "type":"Action"
      },
      "messageWhenValueMissing":{
         "type":"String"
      },
      "readonly":{
         "type":"Boolean"
      },
      "disabled":{
         "type":"Boolean"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "onblur":{
         "type":"Action"
      }
   },
   "lightning:radioGroup":{
      "class":{
         "type":"String"
      },
      "accesskey":{
         "type":"String"
      },
      "onchange":{
         "type":"Action"
      },
      "validity":{
         "type":"Object"
      },
      "required":{
         "type":"Boolean"
      },
      "accesskey":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "type":{
         "type":"String"
      },
      "name":{
         "type":"String",
         "required": True
      },
      "options":{
         "type":"List"
      },
      "value":{
         "type":"Object"
      },
      "validity":{
         "type":"Object"
      },
      "tabindex":{
         "type":"Integer"
      },
      "onfocus":{
         "type":"Action"
      },
      "messageWhenValueMissing":{
         "type":"String"
      },
      "readonly":{
         "type":"Boolean"
      },
      "disabled":{
         "type":"Boolean"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "onblur":{
         "type":"Action"
      }
   },
   "lightning:card":{
      "class":{
         "type":"String"
      },
      "actions":{
         "type":"Component[]"
      },
      "title":{
         "type":"Component[]",
         "required": True
      },
      "iconName":{
         "type":"String"
      },
      "footer":{
         "type":"Component[]"
      },
      "variant":{
         "type":"String"
      }
   },
   "lightning:carousel":{
      "class":{
         "type":"String"
      },
      "disableAutoRefresh":{
         "type":"Boolean"
      },
      "disableAutoScroll":{
         "type":"Boolean"
      },
      "scrollDuration":{
         "type":"Integer"
      },
      "title":{
         "type":"String"
      }
   },
   "aura:template":{
      "auraPreInitBlock":{
         "type":"Component[]"
      },
      "body":{
         "type":"Component[]",
      },
      "bodyClass":{
         "type":"String"
      },
      "defaultBodyClass":{
         "type":"String"
      },
      "doctype":{
         "type":"String"
      },
      "errorMessage":{
         "type":"String"
      },
      "errorTitle":{
         "type":"String"
      },
      "loadingText":{
         "type":"String"
      },
      "title":{
         "type":"String"
      }
   },
   "ui:inputCurrency":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "required":{
         "type":"Boolean"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "format":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "aura:expression":{
      "value":{
         "type":"String"
      }
   },
   "ui:inputPhone":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:outputText":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String",
         "required": True
      },
      "title":{
         "type":"String"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      }
   },
   "lightning:buttonGroup":{
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:container":{
      "alternativeText":{
         "type":"String"
      },
      "class":{
         "type":"String"
      },
      "onerror":{
         "type":"Action"
      },
      "onmessage":{
         "type":"Action"
      },
      "src":{
         "type":"String",
         "required": True
      }
   },
   "lightning:treeGrid":{
      "class":{
         "type":"String"
      },
      "columns":{
         "type":"List"
      },
      "expandedRows":{
         "type":"List"
      },
      "data":{
         "type":"Object"
      },
      "hideCheckboxColumn":{
         "type":"Boolean"
      },
      "isLoading":{
         "type":"Boolean"
      },
      "keyField":{
         "type":"String"
      },
      "maxColumnWidth":{
         "type":"Integer"
      },
      "minColumnWidth":{
         "type":"Integer"
      },
      "onresize":{
         "type":"Action"
      },
      "onrowaction":{
         "type":"Action"
      },
      "onrowselection":{
         "type":"Action"
      },
      "ontoggle":{
         "type":"Action"
      },
      "ontoggleall":{
         "type":"Action"
      },
      "resizeColumnDisabled":{
         "type":"Boolean"
      },
      "rowNumberOffset":{
         "type":"Integer"
      },
      "selectedRows":{
         "type":"List"
      },
      "showRowNumberColumn":{
         "type":"Boolean"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:checkboxGroup":{
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "name":{
         "type":"String",
         "required": True
      },
      "label":{
         "type":"String",
         "required": True
      },
      "options":{
         "type":"List",
         "required": True
      },
      "value":{
         "type":"String[]",
         "required": True
      },
      "messageWhenValueMissing":{
         "type":"String"
      },
      "required":{
         "type":"Boolean"
      },
      "disabled":{
         "type":"Boolean"
      },
      "onblur":{
         "type":"Action"
      },
      "onchange":{
         "type":"Action"
      },
      "onfocus":{
         "type":"Action"
      }
   },
   "lightning:combobox":{
      "name":{
         "type":"String"
      },
      "value":{
         "type":"Object"
      },
      "disabled":{
         "type":"Boolean"
      },
      "readonly":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "validity":{
         "type":"Object"
      },
      "onchange":{
         "type":"Action"
      },
      "accesskey":{
         "type":"String"
      },
      "tabindex":{
         "type":"Integer"
      },
      "onfocus":{
         "type":"Action"
      },
      "onblur":{
         "type":"Action"
      },
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "options":{
         "type":"Object[]",
         "required": True
      },
      "label":{
         "type":"String",
         "required": True
      },
      "placeholder":{
         "type":"String"
      },
      "dropdownAlignment":{
         "type":"String"
      },
      "messageWhenValueMissing":{
         "type":"String"
      }
   },
   "ui:outputNumber":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"BigDecimal",
         "required": True
      },
      "format":{
         "type":"String"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      }
   },
   "ui:outputCheckbox":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "altUnchecked":{
         "type":"String"
      },
      "value":{
         "type":"Boolean",
         "required": True
      },
      "click":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "altChecked":{
         "type":"String"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      }
   },
   "forceChatter:publisher":{
      "context":{
         "type":"String",
         "required": True
      },
      "recordId":{
         "type":"String"
      }
   },
   "forceCommunity:navigationMenuBase":{
      "menuItems":{
         "type":"Object"
      }
   },
   "forceCommunity:notifications":{
      "body":{
         "type":"Component[]"
      }
   },
   "lightning:utilityBarAPI":{
      "body":{
         "type":"Component[]"
      }
   },
   "forceCommunity:routeLink":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "id":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "onClick":{
         "type":"Action"
      },
      "routeInput":{
         "type":"HashMap"
      },
      "title":{
         "type":"String"
      }
   },
   "forceCommunity:waveDashboard":{
      "accessToken":{
         "type":"String"
      },
      "body":{
         "type":"Component[]"
      },
      "dashboardId":{
         "type":"String"
      },
      "developerName":{
         "type":"String"
      },
      "filter":{
         "type":"String"
      },
      "height":{
         "type":"Integer"
      },
      "hideOnerror":{
         "type":"Boolean"
      },
      "title":{
         "type":"String"
      },
      "openLinksInNewWindow":{
         "type":"Boolean"
      },
      "recordId":{
         "type":"String"
      },
      "showHeader":{
         "type":"Boolean"
      },
      "showSharing":{
         "type":"Boolean"
      },
      "showTitle":{
         "type":"Boolean"
      }
   },
   "ui:inputURL":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "aura:handler":{
      "action":{
         "type":"Method"
      },
      "event":{
         "type":"Event"
      },
      "value":{
         "type":"Object"
      },
      "name":{
         "type":"String"
      }
   },
   "lightning:relativeDateTime":{
      "class":{
         "type":"String"
      },
      "value":{
         "type":"Object"
      },
      "title":{
         "type":"String"
      }
   },
   "ui:inputEmail":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "aura:set":{
      "attribute":{
         "type":"String"
      },
      "value":{
         "type":"Object"
      }
   },
   "lightning:menuItem":{
      "checked":{
         "type":"Boolean"
      },
      "class":{
         "type":"String"
      },
      "onfocus":{
         "type":"Action"
      },
      "disabled":{
         "type":"Boolean"
      },
      "value":{
         "type":"String"
      },
      "tabindex":{
         "type":"Integer"
      },
      "iconName":{
         "type":"String"
      },
      "accesskey":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "label":{
         "type":"String"
      }
   },
   "lightning:accordion":{
      "activeSectionName":{
         "type":"String"
      },
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:accordionSection":{
      "actions":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "name":{
         "type":"String"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:avatar":{
      "alternativeText":{
         "type":"String",
         "required": True
      },
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "fallbackIconName":{
         "type":"String"
      },
      "initials":{
         "type":"String"
      },
      "size":{
         "type":"String"
      },
      "src":{
         "type":"String",
         "required": True
      },
      "title":{
         "type":"String"
      },
      "variant":{
         "type":"String"
      }
   },
   "lightning:flow":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "onstatuschange":{
         "type":"Action"
      }
   },
   "lightning:formattedEmail":{
      "body":{
         "type":"Component[]"
      },
      "value":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "onclick":{
         "type":"Action"
      }
   },
   "lightning:formattedLocation":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "latitude":{
         "type":"Decimal",
         "required": True
      },
      "longitude":{
         "type":"Decimal",
         "required": True
      }
   },
   "lightning:inputLocation":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "latitude":{
         "type":"String"
      },
      "longitude":{
         "type":"String"
      },
      "required":{
         "type":"Boolean"
      },
      "disabled":{
         "type":"Boolean"
      },
      "readonly":{
         "type":"Boolean"
      },
      "variant":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "onchange":{
         "type":"Action"
      },
      "onfocus":{
         "type":"Action"
      }
   },
   "lightning:formattedName":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "firstName":{
         "type":"String"
      },
      "format":{
         "type":"String"
      },
      "informalName":{
         "type":"String"
      },
      "lastName":{
         "type":"String"
      },
      "middleName":{
         "type":"String"
      },
      "salutation":{
         "type":"String"
      },
      "suffix":{
         "type":"String"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:inputName":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "readonly":{
         "type":"Boolean"
      },
      "firstName":{
         "type":"String"
      },
      "fieldsToDisplay":{
         "type":"List"
      },
      "informalName":{
         "type":"String"
      },
      "lastName":{
         "type":"String"
      },
      "middleName":{
         "type":"String"
      },
      "options":{
         "type":"List"
      },
      "onblur":{
         "type":"Action"
      },
      "onfocus":{
         "type":"Action"
      },
      "onchange":{
         "type":"Action"
      },
      "salutation":{
         "type":"String"
      },
      "suffix":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:formattedPhone":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "value":{
         "type":"String"
      },
      "onclick":{
         "type":"Action"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:formattedRichText":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "value":{
         "type":"String"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:verticalNavigation":{
      "body":{
         "type":"Component[]"
      },
      "ariaLabel":{
         "type":"String"
      },
      "class":{
         "type":"String"
      },
      "compact":{
         "type":"Boolean"
      },
      "onbeforeselect":{
         "type":"Action"
      },
      "onselect":{
         "type":"Action"
      },
      "selectedItem":{
         "type":"String"
      },
      "shaded":{
         "type":"Boolean"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:workspaceAPI":{
      "body":{
         "type":"Component[]"
      }
   },
   "lightning:verticalNavigationOverflow":{
      "body":{
         "type":"Component[]"
      }
   },
   "lightning:verticalNavigationSection":{
      "body":{
         "type":"Component[]"
      },
      "label":{
         "type":"String",
         "required": True
      }
   },
   "lightning:verticalNavigationItem":{
      "body":{
         "type":"Component[]"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "class":{
         "type":"String"
      },
      "name":{
         "type":"String",
         "required": True
      },
      "href":{
         "type":"String"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:verticalNavigationItemIcon":{
      "body":{
         "type":"Component[]"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "class":{
         "type":"String"
      },
      "name":{
         "type":"String",
         "required": True
      },
      "href":{
         "type":"String"
      },
      "iconName":{
         "type":"String"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:verticalNavigationItemBadge":{
      "body":{
         "type":"Component[]"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "class":{
         "type":"String"
      },
      "name":{
         "type":"String",
         "required": True
      },
      "href":{
         "type":"String"
      },
      "badgeCount":{
         "type":"Integer"
      },
      "assistiveText":{
         "type":"String"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:inputRichText":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "variant":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "ariaLabel":{
         "type":"String"
      },
      "ariaLabelledby":{
         "type":"String"
      },
      "ariaDescribedby":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "value":{
         "type":"Boolean"
      },
      "disabledCategories":{
         "type":"List"
      },
      "messageWhenBadInput":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "onfocus":{
         "type":"Action"
      },
      "placeholder":{
         "type":"String"
      },
      "tabindex":{
         "type":"Integer"
      }
   },
   "lightning:helptext":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "content":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "iconName":{
         "type":"String"
      }
   },
   "lightning:formattedUrl":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "value":{
         "type":"String"
      },
      "target":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "tooltip":{
         "type":"String"
      },
      "onclick":{
         "type":"Action"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:formattedTime":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "value":{
         "type":"Integer"
      },
      "title":{
         "type":"String"
      }
   },
   "lightning:formattedText":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "value":{
         "type":"Integer"
      },
      "title":{
         "type":"String"
      },
      "linkify":{
         "type":"Boolean"
      }
   },
   "lightning:formattedAddress":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "country":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "longitude":{
         "type":"Decimal"
      },
      "latitude":{
         "type":"Decimal"
      },
      "postalCode":{
         "type":"String"
      },
      "province":{
         "type":"String"
      },
      "street":{
         "type":"String"
      },
      "city":{
         "type":"String"
      }
   },
   "lightning:inputAddress":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "country":{
         "type":"String"
      },
      "countryLabel":{
         "type":"String"
      },
      "countryOptions":{
         "type":"List"
      },
      "disabled":{
         "type":"Boolean"
      },
      "readonly":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "longitude":{
         "type":"Decimal"
      },
      "latitude":{
         "type":"Decimal"
      },
      "postalCode":{
         "type":"String"
      },
      "postalCodeLbael":{
         "type":"String"
      },
      "province":{
         "type":"String"
      },
      "provinceLabel":{
         "type":"String"
      },
      "provinceOptions":{
         "type":"List"
      },
      "street":{
         "type":"String"
      },
      "streetLabel":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "onchange":{
         "type":"Action"
      },
      "onfocus":{
         "type":"Action"
      },
      "city":{
         "type":"String"
      },
      "cityLabel":{
         "type":"String"
      },
      "variant":{
         "type":"String"
      }
   },
   "lightning:dynamicIcon":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "option":{
         "type":"String"
      },
      "type":{
         "type":"String",
         "required": True
      },
      "title":{
         "type":"String"
      },
      "alternativeText":{
         "type":"String"
      },
      "onclick":{
         "type":"Action"
      }
   },
   "lightning:flexipageRegionInfo":{
      "body":{
         "type":"Component[]"
      },
      "width":{
         "type":"String"
      }
   },
   "lightning:fileCard":{
      "body":{
         "type":"Component[]"
      },
      "fieldId":{
         "type":"String"
      }
   },
   "lightning:fileUpload":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "recordId":{
         "type":"String",
         "required": True
      },
      "multiple":{
         "type":"Boolean"
      },
      "name":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "accept":{
         "type":"List"
      },
      "onuploadfinished":{
         "type":"Action"
      }
   },
   "lightning:slider":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "value":{
         "type":"Integer"
      },
      "variant":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "readonly":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "variant":{
         "type":"String"
      },
      "onchange":{
         "type":"String"
      },
      "step":{
         "type":"String"
      },
      "size":{
         "type":"String"
      },
      "type":{
         "type":"String"
      },
      "onfocus":{
         "type":"Action"
      },
      "onblur":{
         "type":"Action"
      },
      "label":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "messageWhenBadInput":{
         "type":"String"
      },
      "messageWhenPatternMismatch":{
         "type":"String"
      },
      "messageWhenTypeMismatch":{
         "type":"String"
      },
      "messageWhenValueMissing":{
         "type":"String"
      },
      "messageWhenRangeOverflow":{
         "type":"String"
      },
      "messageWhenRangeUnderflow":{
         "type":"String"
      },
      "messageWhenStepMismatch":{
         "type":"String"
      },
      "messageWhenTooLong":{
         "type":"String"
      },
      "min":{
         "type":"Integer"
      },
      "max":{
         "type":"Integer"
      }
   },
   "lightning:dualListbox":{
      "body":{
         "type":"Component[]"
      },
      "class":{
         "type":"String"
      },
      "value":{
         "type":"Object"
      },
      "variant":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "readonly":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "validity":{
         "type":"Object"
      },
      "onchange":{
         "type":"Action"
      },
      "accesskey":{
         "type":"String"
      },
      "tabindex":{
         "type":"Integer"
      },
      "onfocus":{
         "type":"Action"
      },
      "onblur":{
         "type":"Action"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "sourceLabel":{
         "type":"String",
         "required": True
      },
      "selectedLabel":{
         "type":"String",
         "required": True
      },
      "options":{
         "type":"Object[]",
         "required": True
      },
      "requiredOptions":{
         "type":"List"
      },
      "values":{
         "type":"List"
      },
      "min":{
         "type":"Integer"
      },
      "max":{
         "type":"Integer"
      }
   },
   "ui:outputRichText":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "linkify":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "lightning:spinner":{
      "variant":{
         "type":"String"
      },
      "class":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "size":{
         "type":"String"
      }
   },
   "ui:inputNumber":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "required":{
         "type":"Boolean"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "format":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:inputSelect":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "required":{
         "type":"Boolean"
      },
      "multiple":{
         "type":"Boolean"
      },
      "label":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "options":{
         "type":"List"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:outputEmail":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String",
         "required": True
      },
      "click":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "aura:component":{
      "description":{
         "type":"String"
      },
      "access":{
         "type":"String"
      },
      "implements":{
         "type":"String"
      },
      "extends":{
         "type":"Component"
      },
      "extensible":{
         "type":"Boolean"
      },
      "controller":{
         "type":"String"
      },
      "isTemplate":{
         "type":"Boolean"
      }
   },
   "ui:scrollerWrapper":{
      "class":{
         "type":"String"
      }
   },
   "aura:dependency":{
      "resource":{
         "type":"String"
      },
      "type":{
         "type":"String"
      }
   },
   "forceChatter:feed":{
      "feedDesign":{
         "type":"String"
      },
      "subjectId":{
         "type":"String"
      },
      "type":{
         "type":"String"
      }
   },
   "ui:menuItem":{
      "class":{
         "type":"String"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "selected":{
         "type":"Boolean"
      },
      "hideMenuAfterSelected":{
         "type":"Boolean"
      },
      "type":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "aura:if":{
      "isTrue":{
         "type":"Boolean",
         "required": True
      }
   },
   "ui:outputURL":{
      "class":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "target":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "alt":{
         "type":"String"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "iconClass":{
         "type":"String"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "aura:event":{
      "type":{
         "type":"String"
      }
   },
   "lightning:button":{
      "accesskey":{
         "type":"String"
      },
      "iconPosition":{
         "type":"String"
      },
      "class":{
         "type":"String"
      },
      "value":{
         "type":"String"
      },
      "iconName":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "tabindex":{
         "type":"Integer"
      },
      "onfocus":{
         "type":"Action"
      },
      "variant":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "name":{
         "type":"String"
      },
      "onclick":{
         "type":"Action"
      }
   },
   "ui:spinner":{
      "toggle":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "isVisible":{
         "type":"Boolean"
      }
   },
   "ui:inputText":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "lightning:textarea":{
      "class":{
         "type":"String"
      },
      "variant":{
         "type":"String"
      },
      "onchange":{
         "type":"Action"
      },
      "value":{
         "type":"String"
      },
      "required":{
         "type":"Boolean"
      },
      "accesskey":{
         "type":"String"
      },
      "maxLength":{
         "type":"Integer"
      },
      "minlength":{
         "type":"Integer"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "validity":{
         "type":"Object"
      },
      "title":{
         "type":"String"
      },
      "placeholder":{
         "type":"String"
      },
      "onfocus":{
         "type":"Action"
      },
      "messageWhenTooLong":{
         "type":"String"
      },
      "messageWhenValueMissing":{
         "type":"String"
      },
      "readonly":{
         "type":"Boolean"
      },
      "messageWhenBadInput":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "name":{
         "type":"String",
         "required": True
      },
      "tabindex":{
         "type":"Integer"
      },
      "onblur":{
         "type":"Action"
      }
   },
   "ui:outputTextArea":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String",
         "required": True
      },
      "click":{
         "type":"COMPONENT"
      },
      "linkify":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "aura:interface":{
      "extends":{
         "type":"Component"
      },
      "description":{
         "type":"String"
      },
      "access":{
         "type":"String"
      }
   },
   "force:recordEdit":{
      "recordSave":{
         "type":"Component"
      },
      "onSaveSuccess":{
         "type":"Component"
      },
      "recordId":{
         "type":"String"
      }
   },
   "ui:menuTriggerLink":{
      "mouseup":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "title":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "menuTriggerPress":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "force:recordView":{
      "record":{
         "type":"SObjectRow"
      },
      "recordId":{
         "type":"String"
      },
      "type":{
         "type":"String"
      }
   },
   "lightning:recordViewForm":{
      "class":{
         "type":"String"
      },
      "recordId":{
         "type":"String",
         "required": True
      },
      "objectApiName":{
         "type":"String",
         "required": True
      }
   },
   "lightning:listView":{
      "enableInlineEdit":{
         "type":"Boolean"
      },
      "listName":{
         "type":"String"
      },
      "listName":{
         "type":"String",
         "required": True
      },
      "objectApiName":{
         "type":"String",
         "required": True
      },
      "rows":{
         "type":"Integer"
      },
      "showActionBar":{
         "type":"Boolean"
      },
      "showRowLevelActions":{
         "type":"Boolean"
      }
   },
   "lightning:recordEditForm":{
      "class":{
         "type":"String"
      },
      "objectApiName":{
         "type":"String",
         "required": True
      },
      "onerror":{
         "type":"Action"
      },
      "onload":{
         "type":"Action"
      },
      "onsubmit":{
         "type":"Action"
      },
      "onsuccess":{
         "type":"Action"
      },
      "recordId":{
         "type":"String"
      },
      "recordTypeId":{
         "type":"String"
      },
   },
   "lightning:clickToDial":{
      "class":{
         "type":"String"
      },
      "value":{
         "type":"String",
         "required": True
      },
      "title":{
         "type":"String"
      },
      "recordId":{
         "type":"String"
      },
      "prams":{
         "type":"String"
      },
   },
   "force:recordData":{
      "fields":{
         "type":"String[]"
      },
      "layoutType":{
         "type":"String"
      },
      "targetRecord":{
         "type":"Object"
      },
      "targetRecord":{
         "type":"Object"
      },
      "recordId":{
         "type":"String",
         "required": True
      },
      "targetError":{
         "type":"String"
      },
      "mode":{
         "type":"String"
      },
      "recordUpdated":{
         "type":"COMPONENT"
      }
   }
}