tag_dict = {
   "aura:unescapedHtml":{
      "value":{
         "type":"String"
      }
   },
   "lightning:formattedDateTime":{
      "hour12":{
         "type":"Boolean"
      },
      "day":{
         "type":"String"
      },
      "value":{
         "type":"Object",
         "required": True
      },
      "timeZone":{
         "type":"String"
      },
      "weekday":{
         "type":"String"
      },
      "timeZoneName":{
         "type":"String"
      },
      "month":{
         "type":"String"
      },
      "second":{
         "type":"String"
      },
      "era":{
         "type":"String"
      },
      "hour":{
         "type":"String"
      },
      "minute":{
         "type":"String"
      },
      "year":{
         "type":"String"
      }
   },
   "aura:iteration":{
      "end":{
         "type":"Integer"
      },
      "items":{
         "type":"List",
         "required":True
      },
      "loaded":{
         "type":"Boolean"
      },
      "template":{
         "type":"Componentdefref[]"
      },
      "var":{
         "type":"String",
         "required":True
      },
      "indexVar":{
         "type":"String"
      },
      "body":{
         "type":"Componentdefref[]"
      },
      "start":{
         "type":"Integer"
      }
   },
   "aura:attribute":{
      "required":{
         "type":"Boolean"
      },
      "description":{
         "type":"String"
      },
      "access":{
         "type":"String"
      },
      "default":{
         "type":"String"
      },
      "type":{
         "type":"String"
      },
      "name":{
         "type":"String"
      }
   },
   "lightning:tab":{
      "onblur":{
         "type":"Action"
      },
      "tabindex":{
         "type":"Integer"
      },
      "onfocus":{
         "type":"Action"
      },
      "title":{
         "type":"String"
      },
      "accesskey":{
         "type":"String"
      },
      "id":{
         "type":"String"
      }
   },
   "auraStorage:init":{
      "debugLoggingEnabled":{
         "type":"Boolean"
      },
      "persistent":{
         "type":"Boolean"
      },
      "clearStorageOnInit":{
         "type":"Boolean"
      },
      "defaultAutoRefreshInterval":{
         "type":"Integer"
      },
      "defaultExpiration":{
         "type":"Integer"
      },
      "maxSize":{
         "type":"Integer"
      },
      "version":{
         "type":"String"
      },
      "secure":{
         "type":"Boolean"
      },
      "name":{
         "type":"String",
         "required": True
      }
   },
   "lightning:tabset":{
      "variant":{
         "type":"String"
      },
      "class":{
         "type":"String"
      },
      "selectedTabid":{
         "type":"String"
      },
      "onselect":{
         "type":"Action"
      }
   },
   "ui:inputRadio":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "name":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "text":{
         "type":"String"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "required":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "aura:method":{
      "action":{
         "type":"Expression"
      },
      "description":{
         "type":"String"
      },
      "access":{
         "type":"String"
      },
      "name":{
         "type":"String"
      }
   },
   "lightning:Input":{
      "class":{
         "type":"String"
      },
      "validity":{
         "type":"Object"
      },
      "messageWhenPatternMismatch":{
         "type":"String"
      },
      "value":{
         "type":"Object"
      },
      "accesskey":{
         "type":"String"
      },
      "maxLength":{
         "type":"Integer"
      },
      "minlength":{
         "type":"Integer"
      },
      "type":{
         "type":"String"
      },
      "name":{
         "type":"String",
         "required": True
      },
      "checked":{
         "type":"Boolean"
      },
      "readonly":{
         "type":"Boolean"
      },
      "onfocus":{
         "type":"Action"
      },
      "max":{
         "type":"Decimal"
      },
      "pattern":{
         "type":"String"
      },
      "messageWhenBadInput":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "messageWhenRangeOverflow":{
         "type":"String"
      },
      "messageWhenStepMismatch":{
         "type":"String"
      },
      "onchange":{
         "type":"Action"
      },
      "required":{
         "type":"Boolean"
      },
      "messageWhenValueMissing":{
         "type":"String"
      },
      "min":{
         "type":"Decimal"
      },
      "step":{
         "type":"Object"
      },
      "messageWhenTypeMismatch":{
         "type":"String"
      },
      "formatter":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "messageWhenTooLong":{
         "type":"String"
      },
      "messageWhenRangeUnderflow":{
         "type":"String"
      },
      "placeholder":{
         "type":"String"
      },
      "tabindex":{
         "type":"Integer"
      }
   },
   "lightning:layout":{
      "pullToBoundary":{
         "type":"Boolean"
      },
      "class":{
         "type":"String"
      },
      "verticalAlign":{
         "type":"String"
      },
      "horizontalAlign":{
         "type":"String"
      },
      "multipleRows":{
         "type":"Boolean"
      }
   },
   "lightning:layoutItem":{
      "class":{
         "type":"String"
      },
      "smallDeviceSize":{
         "type":"Integer"
      },
      "flexibility":{
         "type":"Object"
      },
      "largeDeviceSize":{
         "type":"Integer"
      },
      "padding":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "mediumDeviceSize":{
         "type":"Integer"
      }
   },
   "ui:inputDate":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "format":{
         "type":"String"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "langLocale":{
         "type":"String"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "displayDatePicker":{
         "type":"Boolean"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "required":{
         "type":"Boolean"
      },
      "labelClass":{
         "type":"String"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:inputSelectOption":{
      "mouseup":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "click":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "name":{
         "type":"String"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "text":{
         "type":"String"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:outputPhone":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String",
         "required": True
      },
      "click":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "ui:outputCurrency":{
      "class":{
         "type":"String"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"BigDecimal",
         "required": True
      },
      "currencySymbol":{
         "type":"String"
      },
      "currencyCode":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "format":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "ltng:require":{
      "afterScriptsLoaded":{
         "type":"COMPONENT"
      },
      "styles":{
         "type":"String[]"
      },
      "scripts":{
         "type":"String[]"
      },
      "beforeLoadingResources":{
         "type":"COMPONENT"
      }
   },
   "ui:inputRichText":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "resizable":{
         "type":"Boolean"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "required":{
         "type":"Boolean"
      },
      "label":{
         "type":"String"
      },
      "width":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"ArrayList"
      },
      "placeholder":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "rows":{
         "type":"Integer"
      },
      "value":{
         "type":"Boolean"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "height":{
         "type":"String"
      },
      "cols":{
         "type":"Integer"
      },
      "readonly":{
         "type":"Boolean"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:menuTrigger":{
      "class":{
         "type":"String"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "title":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "menuTriggerPress":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:outputDate":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String",
         "required": True
      },
      "langLocale":{
         "type":"String"
      },
      "format":{
         "type":"String"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "lightning:icon":{
      "iconName":{
         "type":"String",
         "required": True
      },
      "class":{
         "type":"String"
      },
      "alternativeText":{
         "type":"String"
      },
      "size":{
         "type":"String"
      },
      "variant":{
         "type":"String"
      }
   },
   "ui:button":{
      "buttonTitle":{
         "type":"String"
      },
      "labelClass":{
         "type":"String"
      },
      "class":{
         "type":"String"
      },
      "press":{
         "type":"COMPONENT"
      },
      "buttonType":{
         "type":"String"
      },
      "accesskey":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "label":{
         "type":"String"
      }
   },
   "lightning:badge":{
      "class":{
         "type":"String"
      },
      "label":{
         "type":"String",
         "required": True
      }
   },
   "ui:inputTextArea":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "resizable":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "placeholder":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "rows":{
         "type":"Integer"
      },
      "value":{
         "type":"Boolean"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "cols":{
         "type":"Integer"
      },
      "readonly":{
         "type":"Boolean"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "ui:message":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "closable":{
         "type":"Boolean"
      },
      "severity":{
         "type":"String"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "title":{
         "type":"String"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "lightning:formattedNumber":{
      "minimumIntegerDigits":{
         "type":"Integer"
      },
      "value":{
         "type":"Decimal"
      },
      "maximumSignificantDigits":{
         "type":"Integer"
      },
      "currencyCode":{
         "type":"String"
      },
      "minimumFractionDigits":{
         "type":"Integer"
      },
      "style":{
         "type":"String"
      },
      "maximumFractionDigits":{
         "type":"Integer"
      },
      "currencyDisplayAs":{
         "type":"String"
      },
      "minimumSignificantDigits":{
         "type":"Integer"
      }
   },
   "ui:checkboxMenuItem":{
      "class":{
         "type":"String"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "selected":{
         "type":"Boolean"
      },
      "hideMenuAfterSelected":{
         "type":"Boolean"
      },
      "type":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "aura:registerEvent":{
      "type":{
         "type":"String"
      },
      "name":{
         "type":"String"
      }
   },
   "force:inputField":{
      "change":{
         "type":"Component"
      },
      "class":{
         "type":"String"
      },
      "value":{
         "type":"Object"
      },
      "required":{
         "type":"Boolean"
      }
   },
   "ui:actionMenuItem":{
      "class":{
         "type":"String"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "selected":{
         "type":"Boolean"
      },
      "hideMenuAfterSelected":{
         "type":"Boolean"
      },
      "type":{
         "type":"String"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "label":{
         "type":"String"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "aura:html":{
      "tag":{
         "type":"String"
      },
      "HTMLAttributes":{
         "type":"Map"
      },
      "body":{
         "type":"Component[]"
      }
   },
   "force:canvasApp":{
      "displayLocation":{
         "type":"String"
      },
      "border":{
         "type":"String"
      },
      "watermark":{
         "type":"Boolean"
      },
      "maxHeight":{
         "type":"String"
      },
      "developerName":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "sublocation":{
         "type":"String"
      },
      "containerId":{
         "type":"String"
      },
      "width":{
         "type":"String"
      },
      "parameters":{
         "type":"String"
      },
      "scrolling":{
         "type":"String"
      },
      "onCanvasAppLoad":{
         "type":"String"
      },
      "onCanvasAppError":{
         "type":"String"
      },
      "maxWidth":{
         "type":"String"
      },
      "height":{
         "type":"String"
      },
      "applicationName":{
         "type":"String"
      },
      "namespacePrefix":{
         "type":"String"
      },
      "onCanvasSubscribed":{
         "type":"String"
      },
      "canvasId":{
         "type":"String"
      },
      "referenceId":{
         "type":"Id"
      }
   },
   "ui:menuList":{
      "class":{
         "type":"String"
      },
      "menuItems":{
         "type":"List"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "menuCollapse":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "visible":{
         "type":"Boolean"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "closeOnTabKey":{
         "type":"Boolean"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "menuExpand":{
         "type":"COMPONENT"
      },
      "autoPosition":{
         "type":"Boolean"
      },
      "menuFocusChange":{
         "type":"COMPONENT"
      },
      "closeOnClickOutside":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "menuSelect":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      }
   },
   "lightning:buttonMenu":{
      "class":{
         "type":"String"
      },
      "iconSize":{
         "type":"String"
      },
      "alternativeText":{
         "type":"String"
      },
      "value":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "iconName":{
         "type":"String"
      },
      "visible":{
         "type":"Boolean"
      },
      "accesskey":{
         "type":"String"
      },
      "name":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "tabindex":{
         "type":"Integer"
      },
      "onfocus":{
         "type":"Action"
      },
      "variant":{
         "type":"String"
      },
      "onselect":{
         "type":"Action"
      },
      "disabled":{
         "type":"Boolean"
      },
      "menuAlignment":{
         "type":"String"
      }
   },
   "ui:inputCheckbox":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "name":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "text":{
         "type":"String"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "required":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:inputSecret":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "forceChatter:fullFeed":{
      "subjectId":{
         "type":"String"
      },
      "type":{
         "type":"String"
      },
      "handleNavigationEvents":{
         "type":"Boolean"
      }
   },
   "ui:inputDefaultError":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String[]"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "ui:menu":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "force:outputField":{
      "class":{
         "type":"String"
      },
      "value":{
         "type":"Object"
      }
   },
   "lightning:buttonIcon":{
      "class":{
         "type":"String"
      },
      "alternativeText":{
         "type":"String",
         "required": True
      },
      "value":{
         "type":"String"
      },
      "size":{
         "type":"String"
      },
      "iconName":{
         "type":"String",
         "required": True
      },
      "accesskey":{
         "type":"String"
      },
      "name":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "tabindex":{
         "type":"Integer"
      },
      "onfocus":{
         "type":"Action"
      },
      "variant":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "onclick":{
         "type":"Action"
      }
   },
   "ui:outputDateTime":{
      "class":{
         "type":"String"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String",
         "required": True
      },
      "timezone":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "format":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "langLocale":{
         "type":"String"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "ui:inputDateTime":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "format":{
         "type":"String"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "langLocale":{
         "type":"String"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "displayDatePicker":{
         "type":"Boolean"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "required":{
         "type":"Boolean"
      },
      "labelClass":{
         "type":"String"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:menuItemSeparator":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "lightning:select":{
      "class":{
         "type":"String"
      },
      "onchange":{
         "type":"Action"
      },
      "value":{
         "type":"String"
      },
      "required":{
         "type":"Boolean"
      },
      "accesskey":{
         "type":"String"
      },
      "name":{
         "type":"String",
         "required": True
      },
      "validity":{
         "type":"Object"
      },
      "tabindex":{
         "type":"Integer"
      },
      "onfocus":{
         "type":"Action"
      },
      "messageWhenValueMissing":{
         "type":"String"
      },
      "readonly":{
         "type":"Boolean"
      },
      "disabled":{
         "type":"Boolean"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "onblur":{
         "type":"Action"
      }
   },
   "lightning:card":{
      "class":{
         "type":"String"
      },
      "actions":{
         "type":"Component[]"
      },
      "title":{
         "type":"Component[]",
         "required": True
      },
      "iconName":{
         "type":"String"
      },
      "footer":{
         "type":"Component[]"
      },
      "variant":{
         "type":"String"
      }
   },
   "ui:inputCurrency":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "required":{
         "type":"Boolean"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "format":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "aura:expression":{
      "value":{
         "type":"String"
      }
   },
   "ui:inputPhone":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:outputText":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String",
         "required": True
      },
      "title":{
         "type":"String"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      }
   },
   "lightning:buttonGroup":{
      "class":{
         "type":"String"
      }
   },
   "ui:outputNumber":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"BigDecimal",
         "required": True
      },
      "format":{
         "type":"String"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      }
   },
   "ui:outputCheckbox":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "altUnchecked":{
         "type":"String"
      },
      "value":{
         "type":"Boolean",
         "required": True
      },
      "click":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "altChecked":{
         "type":"String"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      }
   },
   "forceChatter:publisher":{
      "context":{
         "type":"String",
         "required": True
      },
      "recordId":{
         "type":"String"
      }
   },
   "ui:inputURL":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "aura:handler":{
      "action":{
         "type":"Method"
      },
      "event":{
         "type":"Event"
      },
      "value":{
         "type":"Object"
      },
      "name":{
         "type":"String"
      }
   },
   "ui:inputEmail":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "aura:set":{
      "attribute":{
         "type":"String"
      },
      "value":{
         "type":"Object"
      }
   },
   "lightning:menuItem":{
      "checked":{
         "type":"Boolean"
      },
      "class":{
         "type":"String"
      },
      "onfocus":{
         "type":"Action"
      },
      "disabled":{
         "type":"Boolean"
      },
      "value":{
         "type":"String"
      },
      "tabindex":{
         "type":"Integer"
      },
      "iconName":{
         "type":"String"
      },
      "accesskey":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "label":{
         "type":"String"
      }
   },
   "ui:outputRichText":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "linkify":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "lightning:spinner":{
      "variant":{
         "type":"String"
      },
      "class":{
         "type":"String"
      },
      "size":{
         "type":"String"
      }
   },
   "ui:inputNumber":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "required":{
         "type":"Boolean"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "format":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:inputSelect":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "required":{
         "type":"Boolean"
      },
      "multiple":{
         "type":"Boolean"
      },
      "label":{
         "type":"String"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "options":{
         "type":"List"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "ui:outputEmail":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String",
         "required": True
      },
      "click":{
         "type":"COMPONENT"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "aura:component":{
      "description":{
         "type":"String"
      },
      "access":{
         "type":"String"
      },
      "implements":{
         "type":"String"
      },
      "extends":{
         "type":"Component"
      },
      "extensible":{
         "type":"Boolean"
      },
      "controller":{
         "type":"String"
      },
      "isTemplate":{
         "type":"Boolean"
      }
   },
   "ui:scrollerWrapper":{
      "class":{
         "type":"String"
      }
   },
   "aura:dependency":{
      "resource":{
         "type":"String"
      },
      "type":{
         "type":"String"
      }
   },
   "forceChatter:feed":{
      "feedDesign":{
         "type":"String"
      },
      "subjectId":{
         "type":"String"
      },
      "type":{
         "type":"String"
      }
   },
   "ui:menuItem":{
      "class":{
         "type":"String"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "click":{
         "type":"COMPONENT"
      },
      "selected":{
         "type":"Boolean"
      },
      "hideMenuAfterSelected":{
         "type":"Boolean"
      },
      "type":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "aura:if":{
      "isTrue":{
         "type":"Boolean",
         "required": True
      }
   },
   "ui:outputURL":{
      "class":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "target":{
         "type":"String"
      },
      "title":{
         "type":"String"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "alt":{
         "type":"String"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "iconClass":{
         "type":"String"
      },
      "mouseup":{
         "type":"COMPONENT"
      }
   },
   "aura:event":{
      "type":{
         "type":"String"
      }
   },
   "lightning:button":{
      "iconPosition":{
         "type":"String"
      },
      "class":{
         "type":"String"
      },
      "value":{
         "type":"String"
      },
      "iconName":{
         "type":"String"
      },
      "label":{
         "type":"String"
      },
      "onblur":{
         "type":"Action"
      },
      "tabindex":{
         "type":"Integer"
      },
      "onfocus":{
         "type":"Action"
      },
      "variant":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "name":{
         "type":"String"
      },
      "onclick":{
         "type":"Action"
      }
   },
   "ui:spinner":{
      "toggle":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "isVisible":{
         "type":"Boolean"
      }
   },
   "ui:inputText":{
      "class":{
         "type":"String"
      },
      "onClearErrors":{
         "type":"COMPONENT"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"Boolean"
      },
      "required":{
         "type":"Boolean"
      },
      "change":{
         "type":"COMPONENT"
      },
      "requiredIndicatorClass":{
         "type":"String"
      },
      "cut":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "size":{
         "type":"Integer"
      },
      "updateOn":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "onError":{
         "type":"COMPONENT"
      },
      "errors":{
         "type":"List"
      },
      "click":{
         "type":"COMPONENT"
      },
      "labelClass":{
         "type":"String"
      },
      "maxlength":{
         "type":"Integer"
      },
      "paste":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "placeholder":{
         "type":"String"
      },
      "copy":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "lightning:textarea":{
      "class":{
         "type":"String"
      },
      "onchange":{
         "type":"Action"
      },
      "value":{
         "type":"Object"
      },
      "required":{
         "type":"Boolean"
      },
      "accesskey":{
         "type":"String"
      },
      "maxLength":{
         "type":"Integer"
      },
      "minlength":{
         "type":"Integer"
      },
      "label":{
         "type":"String",
         "required": True
      },
      "validity":{
         "type":"Object"
      },
      "placeholder":{
         "type":"String"
      },
      "onfocus":{
         "type":"Action"
      },
      "messageWhenTooLong":{
         "type":"String"
      },
      "messageWhenValueMissing":{
         "type":"String"
      },
      "readonly":{
         "type":"Boolean"
      },
      "messageWhenBadInput":{
         "type":"String"
      },
      "disabled":{
         "type":"Boolean"
      },
      "name":{
         "type":"String",
         "required": True
      },
      "tabindex":{
         "type":"Integer"
      },
      "onblur":{
         "type":"Action"
      }
   },
   "ui:outputTextArea":{
      "mousedown":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "value":{
         "type":"String",
         "required": True
      },
      "click":{
         "type":"COMPONENT"
      },
      "linkify":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "mouseup":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      }
   },
   "aura:interface":{
      "extends":{
         "type":"Component"
      },
      "description":{
         "type":"String"
      },
      "access":{
         "type":"String"
      }
   },
   "force:recordEdit":{
      "recordSave":{
         "type":"Component"
      },
      "onSaveSuccess":{
         "type":"Component"
      },
      "recordId":{
         "type":"String"
      }
   },
   "ui:menuTriggerLink":{
      "mouseup":{
         "type":"COMPONENT"
      },
      "class":{
         "type":"String"
      },
      "keyup":{
         "type":"COMPONENT"
      },
      "select":{
         "type":"COMPONENT"
      },
      "mouseout":{
         "type":"COMPONENT"
      },
      "focus":{
         "type":"COMPONENT"
      },
      "title":{
         "type":"String"
      },
      "click":{
         "type":"COMPONENT"
      },
      "mouseover":{
         "type":"COMPONENT"
      },
      "label":{
         "type":"String"
      },
      "mousedown":{
         "type":"COMPONENT"
      },
      "keydown":{
         "type":"COMPONENT"
      },
      "dblclick":{
         "type":"COMPONENT"
      },
      "menuTriggerPress":{
         "type":"COMPONENT"
      },
      "keypress":{
         "type":"COMPONENT"
      },
      "disabled":{
         "type":"Boolean"
      },
      "mousemove":{
         "type":"COMPONENT"
      },
      "blur":{
         "type":"COMPONENT"
      }
   },
   "force:recordView":{
      "record":{
         "type":"SObjectRow"
      },
      "recordId":{
         "type":"String"
      },
      "type":{
         "type":"String"
      }
   }
}