tag_dict = {
    'aura:attribute' : {
        'name':'String', 
        'type':'String', 
        'access':'String',
        'default':'String',
        'required':'Boolean',
        'description':'String'},

    'aura:if' : {'isTrue':'Boolean'},

    'aura:iteration': {
        'items': 'List',
        'var': 'String',
        'indexVar': 'String',
        'start': 'Integer',
        'end': 'Integer',
        'loaded': 'Boolean',
        'body': 'Componentdefref[]',
        'template': 'Componentdefref[]'},

    'aura:set': {
        'attribute':'String',
        'value':'Object'},

    'aura:event':{
        'type' : 'String'
    },

    'aura:registerEvent' :{
        'name': 'String',
        'type': 'String'},

    'aura:handler': {
        'name':'String',
        'event':'Event',
        'action':'Method',
        'value':'Object'},
    
    'aura:component' : {
        'access':'String', 
        'controller':'String', 
        'description':'String',
        'extends':'Component',
        'extensible':'Boolean',
        'implements':'String',
        'isTemplate':'Boolean'},

    'aura:dependency' : {
                'resource':'String', 
                'type':'String'},

    'aura:interface' : {
                'access':'String',
                'description':'String',
                'extends':'Component'},

    'aura:method' : {
                'name':'String', 
                'action':'Expression',
                'access':'String',
                'description':'String'},

    'aura:expression' : {'value' :'String'},

    'aura:html' : {
                'body':'Component[]', 
                'HTMLAttributes':'Map', 
                'tag':'String'},

    'aura:renderif' : {'isTrue':'Boolean'},

    'aura:unescapedHtml' : {'value':'String'},

    'auraStorage:init' : {
                'clearStorageOnInit':'Boolean', 
                'debugLoggingEnabled':'Boolean', 
                'defaultAutoRefreshInterval':'Integer',
                'defaultExpiration':'Integer',
                'maxSize':'Integer',
                'name':'String',
                'persistent':'Boolean',
                'secure':'Boolean',
                'version':'String'},

    'force:canvasApp' : {
                'applicationName':'String', 
                'border':'String', 
                'canvasId':'String',
                'containerId':'String',
                'developerName':'String',
                'displayLocation':'String',
                'height':'String',
                'maxHeight':'String',
                'maxWidth':'String',
                'namespacePrefix':'String',
                'onCanvasAppError':'String',
                'onCanvasAppLoad':'String',
                'onCanvasSubscribed':'String',
                'parameters':'String',
                'referenceId':'Id',
                'scrolling':'String',
                'sublocation':'String',
                'title':'String',
                'watermark':'Boolean',
                'width':'String'},

    'force:inputField' : {
                'class':'String', 
                'required':'Boolean',
                'value':'Object',
                'change':'Component'},

    'force:outputField' : {
                'class':'String', 
                'value':'Object'},

    'force:recordEdit' : {
                'recordId':'String', 
                'recordSave':'Component',
                'onSaveSuccess':'Component'},

    'force:recordView' : {
                'record':'SObjectRow', 
                'recordId':'String',
                'type':'String'},

    'forceChatter:feed' : {
                'feedDesign':'String', 
                'subjectId':'String',
                'type':'String'},

    'forceChatter:fullFeed' : {
                'handleNavigationEvents':'Boolean', 
                'subjectId':'String',
                'type':'String'},

    'forceChatter:publisher' : {
                'context':'String', 
                'recordId':'String'},

    'lightning:badge' : {
                'class':'String',
                'label':'String'},

    'lightning:button' : {
                'class':'String', 
                'disabled':'Boolean',
                'iconName':'String',
                'iconPosition':'String',
                'label':'String',
                'name':'String',
                'onblur':'Action',
                'onclick':'Action',
                'onfocus':'Action',
                'tabindex':'Integer',
                'value':'String',
                'variant':'String'},

    'lightning:buttonGroup' : {'class':'String'},

    'lightning:buttonIcon' : {
                'accesskey':'String',
                'alternativeText':'String',
                'class':'String', 
                'disabled':'Boolean',
                'iconName':'String',
                'name':'String',
                'onblur':'Action',
                'onclick':'Action',
                'onfocus':'Action',
                'size':'String',
                'tabindex':'Integer',
                'value':'String',
                'variant':'String'},

    'lightning:buttonMenu' : {
                'accesskey':'String',
                'alternativeText':'String',
                'class':'String', 
                'disabled':'Boolean',
                'iconName':'String',
                'iconSize':'String',
                'menuAlignment':'String',
                'name':'String',
                'onblur':'Action',
                'onselect':'Action',
                'onfocus':'Action',
                'title':'String',
                'tabindex':'Integer',
                'value':'String',
                'variant':'String',
                'visible':'Boolean'},

    'lightning:card' : {
                'actions':'Component[]',
                'class':'String', 
                'footer':'Component[]',
                'iconName':'String',
                'title':'Component[]',
                'variant':'String'},

    'lightning:formattedDateTime' : {
                'day':'String',
                'era':'String',
                'hour':'String', 
                'hour12':'Boolean',
                'minute':'String',
                'month':'String',
                'second':'String',
                'timeZone':'String',
                'timeZoneName':'String',
                'value':'Object',
                'weekday':'String',
                'year':'String'},

    'lightning:formattedNumber' : {
                'currencyCode':'String',
                'currencyDisplayAs':'String',
                'maximumFractionDigits':'Integer', 
                'maximumSignificantDigits':'Integer',
                'minimumFractionDigits':'Integer',
                'minimumIntegerDigits':'Integer',
                'minimumSignificantDigits':'Integer',
                'style':'String',
                'value':'Decimal'},

    'lightning:icon' : {
                'alternativeText':'String',
                'class':'String', 
                'iconName':'String',
                'size':'String',
                'variant':'String'},

    'lightning:Input' : {
                'accesskey':'String',
                'checked':'Boolean',
                'class':'String', 
                'disabled':'Boolean',
                'formatter':'String',
                'label':'String',
                'max':'Decimal',
                'maxLength':'Integer',
                'messageWhenBadInput':'String',
                'messageWhenPatternMismatch':'String',
                'messageWhenRangeOverflow':'String',
                'messageWhenRangeUnderflow':'String',
                'messageWhenStepMismatch':'String',
                'messageWhenTooLong':'String',
                'messageWhenTypeMismatch':'String',
                'messageWhenValueMissing':'String',
                'min':'Decimal',
                'minlength':'Integer',
                'name':'String',
                'onblur':'Action',
                'onchange':'Action',
                'onfocus':'Action',
                'pattern':'String',
                'placeholder':'String',
                'readonly':'Boolean',
                'required':'Boolean',
                'step':'Object',
                'tabindex':'Integer',
                'type':'String',
                'validity':'Object',
                'value':'Object'},


    'lightning:layout' : {
                'class':'String', 
                'horizontalAlign':'String',
                'multipleRows':'Boolean',
                'pullToBoundary':'Boolean',
                'verticalAlign':'String'},


    'lightning:layoutItem' : {
                'class':'String', 
                'flexibility':'Object',
                'largeDeviceSize':'Integer',
                'mediumDeviceSize':'Integer',
                'smallDeviceSize':'Integer',
                'padding':'String',
                'size':'Integer'},


    'lightning:menuItem' : {
                'accesskey':'String',
                'checked':'Boolean',
                'class':'String', 
                'disabled':'Boolean',
                'iconName':'String',
                'label':'String',
                'onblur':'Action',
                'onfocus':'Action',
                'tabindex':'Integer',
                'title':'String',
                'value':'String'},


    'lightning:select' : {
                'accesskey':'String',
                'class':'String', 
                'disabled':'Boolean',
                'label':'String',
                'messageWhenValueMissing':'String',
                'name':'String',
                'onblur':'Action',
                'onfocus':'Action',
                'onchange':'Action',
                'readonly':'Boolean',
                'required':'Boolean',
                'tabindex':'Integer',
                'validity':'Object',
                'value':'String'},

    'lightning:spinner' : {
                'class':'String',
                'size':'String',
                'variant':'String'},

    'lightning:tab' : {
                'accesskey':'String',
                'id':'String', 
                'onblur':'Action',
                'onfocus':'Action',
                'tabindex':'Integer',
                'title':'String'},

    'lightning:tabset' : {
                'class':'String', 
                'onselect':'Action',
                'selectedTabid':'String',
                'variant':'String'},

    'lightning:textarea' : {
                'accesskey':'String',
                'class':'String', 
                'disabled':'Boolean',
                'label':'String',
                'maxLength':'Integer',
                'messageWhenBadInput':'String',
                'messageWhenTooLong':'String',
                'messageWhenValueMissing':'String',
                'minlength':'Integer',
                'name':'String',
                'onblur':'Action',
                'onchange':'Action',
                'onfocus':'Action',
                'placeholder':'String',
                'readonly':'Boolean',
                'required':'Boolean',
                'tabindex':'Integer',
                'validity':'Object',
                'value':'Object'},

    'ltng:require' : {
                'scripts':'String[]',
                'styles':'String[]',
                'afterScriptsLoaded':'COMPONENT',
                'beforeLoadingResources':'COMPONENT'},

    'ui:actionMenuItem' : {
                'class':'String',
                'disabled':'Boolean',
                'hideMenuAfterSelected':'Boolean',
                'label':'String',
                'selected':'Boolean',
                'type':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT'},

    'ui:button' : {
                'accesskey':'String',
                'buttonTitle':'String',
                'buttonType':'String',
                'class':'String',
                'disabled':'Boolean',
                'label':'String',
                'labelClass':'String',
                'press':'COMPONENT'},

    'ui:checkboxMenuItem' : {
                'class':'String',
                'disabled':'Boolean',
                'hideMenuAfterSelected':'Boolean',
                'label':'String',
                'selected':'Boolean',
                'type':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT'},

    'ui:inputCheckbox' : {
                'class':'String',
                'disabled':'Boolean',
                'errors':'List',
                'label':'String',
                'labelClass':'String',
                'name':'String',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'text':'String',
                'updateOn':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:inputCurrency' : {
                'class':'String',
                'disabled':'Boolean',
                'errors':'List',
                'format':'String',
                'label':'String',
                'labelClass':'String',
                'maxlength':'Integer',
                'placeholder':'String',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'size':'Integer',
                'updateOn':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:inputDate' : {
                'class':'String',
                'disabled':'Boolean',
                'errors':'List',
                'displayDatePicker':'Boolean',
                'format':'String',
                'label':'String',
                'labelClass':'String',
                'langLocale':'String',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'updateOn':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:inputDateTime' : {
                'class':'String',
                'disabled':'Boolean',
                'errors':'List',
                'displayDatePicker':'Boolean',
                'format':'String',
                'label':'String',
                'labelClass':'String',
                'langLocale':'String',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'updateOn':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:inputDefaultError' : {
                'class':'String',
                'value':'String[]',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:inputEmail' : {
                'class':'String',
                'disabled':'Boolean',
                'errors':'List',
                'label':'String',
                'labelClass':'String',
                'maxlength':'Integer',
                'placeholder':'String',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'size':'Integer',
                'updateOn':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:inputNumber' : {
                'class':'String',
                'disabled':'Boolean',
                'errors':'List',
                'format':'String',
                'label':'String',
                'labelClass':'String',
                'maxlength':'Integer',
                'placeholder':'String',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'size':'Integer',
                'updateOn':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:inputPhone' : {
                'class':'String',
                'disabled':'Boolean',
                'errors':'List',
                'label':'String',
                'labelClass':'String',
                'maxlength':'Integer',
                'placeholder':'String',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'size':'Integer',
                'updateOn':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:inputRadio' : {
                'class':'String',
                'disabled':'Boolean',
                'errors':'List',
                'label':'String',
                'labelClass':'String',
                'name':'String',
                'text':'String',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'updateOn':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:inputRichText' : {
                'class':'String',
                'cols':'Integer',
                'disabled':'Boolean',
                'errors':'ArrayList',
                'height':'String',
                'label':'String',
                'labelClass':'String',
                'maxlength':'Integer',
                'placeholder':'String',
                'readonly':'Boolean',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'resizable':'Boolean',
                'rows':'Integer',
                'updateOn':'String',
                'value':'Boolean',
                'width':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:inputSecret' : {
                'class':'String',
                'disabled':'Boolean',
                'errors':'List',
                'label':'String',
                'labelClass':'String',
                'maxlength':'Integer',
                'placeholder':'String',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'size':'Integer',
                'updateOn':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:inputSelect' : {
                'class':'String',
                'disabled':'Boolean',
                'errors':'List',
                'label':'String',
                'labelClass':'String',
                'multiple':'Boolean',
                'options':'List',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'updateOn':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:inputSelectOption' : {
                'class':'String',
                'disabled':'Boolean',
                'label':'String',
                'name':'String',
                'text':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT'},

    'ui:inputText' : {
                'class':'String',
                'disabled':'Boolean',
                'errors':'List',
                'label':'String',
                'labelClass':'String',
                'maxlength':'Integer',
                'placeholder':'String',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'size':'Integer',
                'updateOn':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:inputTextArea' : {
                'class':'String',
                'cols':'Integer',
                'disabled':'Boolean',
                'errors':'List',
                'label':'String',
                'labelClass':'String',
                'maxlength':'Integer',
                'placeholder':'String',
                'readonly':'Boolean',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'resizable':'Boolean',
                'rows':'Integer',
                'updateOn':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:inputURL' : {
                'class':'String',
                'disabled':'Boolean',
                'errors':'List',
                'label':'String',
                'labelClass':'String',
                'maxlength':'Integer',
                'placeholder':'String',
                'required':'Boolean',
                'requiredIndicatorClass':'String',
                'size':'Integer',
                'updateOn':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'cut':'COMPONENT',
                'onError':'COMPONENT',
                'onClearErrors':'COMPONENT',
                'change':'COMPONENT',
                'copy':'COMPONENT',
                'paste':'COMPONENT'},

    'ui:menu' : {
                'class':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:menuItem' : {
                'class':'String',
                'disabled':'Boolean',
                'hideMenuAfterSelected':'Boolean',
                'label':'String',
                'selected':'Boolean',
                'type':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT'},

    'ui:menuItemSeparator' : {
                'class':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:menuList' : {
                'autoPosition':'Boolean',
                'class':'String',
                'closeOnClickOutside':'Boolean',
                'closeOnTabKey':'Boolean',
                'menuItems':'List',
                'visible':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'menuExpand':'COMPONENT',
                'menuSelect':'COMPONENT',
                'menuCollapse':'COMPONENT',
                'menuFocusChange':'COMPONENT'},

    'ui:menuTrigger' : {
                'class':'String',
                'disabled':'Boolean',
                'title':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'menuTriggerPress':'COMPONENT'},

    'ui:menuTriggerLink' : {
                'class':'String',
                'disabled':'Boolean',
                'label':'String',
                'title':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT',
                'select':'COMPONENT',
                'blur':'COMPONENT',
                'focus':'COMPONENT',
                'keypress':'COMPONENT',
                'keyup':'COMPONENT',
                'keydown':'COMPONENT',
                'menuTriggerPress':'COMPONENT'},

    'ui:message' : {
                'class':'String',
                'closable':'Boolean',
                'severity':'String',
                'title':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT'},

    'ui:outputCheckbox' : {
                'altChecked':'String',
                'altUnchecked':'String',
                'class':'String',
                'value':'Boolean',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:outputCurrency' : {
                'class':'String',
                'currencyCode':'String',
                'currencySymbol':'String',
                'format':'String',
                'value':'BigDecimal',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:outputDate' : {
                'class':'String',
                'format':'String',
                'langLocale':'String',
                'value':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:outputDateTime' : {
                'class':'String',
                'format':'String',
                'langLocale':'String',
                'timezone':'String',
                'value':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:outputEmail' : {
                'class':'String',
                'value':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:outputNumber' : {
                'class':'String',
                'format':'String',
                'value':'BigDecimal',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:outputPhone' : {
                'class':'String',
                'value':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:outputRichText' : {
                'class':'String',
                'linkify':'Boolean',
                'value':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:outputText' : {
                'class':'String',
                'title':'String',
                'value':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:outputTextArea' : {
                'class':'String',
                'linkify':'Boolean',
                'value':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:outputURL' : {
                'alt':'String',
                'class':'String',
                'disabled':'Boolean',
                'iconClass':'String',
                'label':'String',
                'target':'String',
                'title':'String',
                'value':'String',
                'dblclick':'COMPONENT',
                'mouseover':'COMPONENT',
                'mouseout':'COMPONENT',
                'mouseup':'COMPONENT',
                'mousemove':'COMPONENT',
                'mousedown':'COMPONENT',
                'click':'COMPONENT'},

    'ui:scrollerWrapper' : {'class':'String'},

    'ui:spinner' : {
                'class':'String',
                'isVisible':'Boolean',
                'toggle':'COMPONENT'}


}